# Generated by Django 4.2.10 on 2025-01-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bike", "0001_initial"),
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wishlist",
            field=models.ManyToManyField(
                blank=True, related_name="wishlisted_by", to="Bike.bike"
            ),
        ),
    ]
