# Generated by Django 4.2.10 on 2025-01-19 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("launch_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("specifications", models.JSONField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="bike_images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bike_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bike_one",
                        to="Bike.bike",
                    ),
                ),
                (
                    "bike_two",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bike_two",
                        to="Bike.bike",
                    ),
                ),
            ],
        ),
    ]
