# Generated by Django 4.2.10 on 2025-03-05 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Bike", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="bike",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Bike.bike"
            ),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="service_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Bike.servicetype"
            ),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="comparison",
            name="bike_one",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bike_one",
                to="Bike.bike",
            ),
        ),
        migrations.AddField(
            model_name="comparison",
            name="bike_two",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bike_two",
                to="Bike.bike",
            ),
        ),
    ]
